version: "3.9"

services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: gis_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/main/resources/db:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lublin -d gis_dashboard"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: